---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-sample
  name: nginx-sample
  namespace: demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-sample
  template:
    metadata:
      labels:
        app: nginx-sample
    spec:
      containers:
      - image: nginx
        name: nginx
